### ISSUE TITLE
Is not working

### ISSUE THREAD

**Issue by josetiznado** [maxoodf/pg_mystem#1]
I had problems trying to install, Can you help me?

**Comment by maxoodf** [comment]
josetiznado,
please describe what are the problems - installation step, errors, PostgreSQL version, OS, compiler version etc.

**Comment by josetiznado** [comment]
its not a problem related to this product, my problem is that i did not know how to contact you, i need a quote from our existing project, i need you to do some modifications

**Comment by maxoodf** [comment]
you can contact me at [max.fomitchev@gmail.com]()

**Comment by josetiznado** [comment]
Thanks, we will contact you, how do i delete this open issue?
